CREATE TABLE PATIENT(
    P_ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    P_NOM VARCHAR2(30) NOT NULL,
    P_PRENOM VARCHAR2(30) NOT NULL,
    P_NUMTEL NUMBER(10),
    TYPE_SERVICE VARCHAR2(50) NOT NULL,
    PAIMENT NUMBER NOT NULL
);
DESCRIBE PATIENT;

ALTER TABLE PATIENT ADD DATE_RENDEZVOUS VARCHAR2(12);



CREATE TABLE DENTAIREEMP(
    E_ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    E_NOM VARCHAR2(30) NOT NULL,
    E_PRENOM VARCHAR2(30) NOT NULL,
    E_NUMTEL NUMBER(10),
    SALAIRE NUMBER,
    PRIME NUMBER
);
DESCRIBE DENTAIREEMP;